"""add social links to Friend model

Revision ID: 419366e86b42
Revises: 
Create Date: 2024-08-03 14:52:35.896284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419366e86b42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('social_links')

    # ### end Alembic commands ###
